version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: garagem_ucsal
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: garagem_db
    ports:
      - "5432:5432"
    volumes:
      - garagem_data:/var/lib/postgresql/data

volumes:
  garagem_data:
